"""
Terminal CLI Runner for the AI Autonomous Research Agent.
Demonstrates:
- Tool 1 (tavily_search) execution
- Tool 2 (summarize_url) execution
- Tool 3 (save_report) execution
- Full ReAct Agent loop with state memory & Human-In-The-Loop terminal confirmation
"""
import os
import sys
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from agent.tools import execute_tavily_search, execute_url_summary, execute_save_report
from agent.graph import build_research_graph


def print_banner():
    print("=" * 70)
    print("  AI AUTONOMOUS RESEARCH AGENT (Groq + LangGraph + Tavily)")
    print("=" * 70)


def check_api_keys():
    load_dotenv()
    groq_key = os.getenv("GROQ_API_KEY")
    tavily_key = os.getenv("TAVILY_API_KEY")

    missing = []
    if not groq_key or groq_key == "your_groq_api_key_here":
        missing.append("GROQ_API_KEY")
    if not tavily_key or tavily_key == "your_tavily_api_key_here":
        missing.append("TAVILY_API_KEY")

    if missing:
        print(f"\n[WARNING] Missing Environment Variable(s): {', '.join(missing)}")
        print("Please configure your .env file or set environment variables before running.\n")
        return False
    return True


def test_individual_tools():
    """Quick verification test of all 3 tools working directly."""
    print("\n--- [TESTING INDIVIDUAL TOOLS] ---")
    
    # 1. Test Tavily Search
    print("\n[1] Testing Tool 1: tavily_search...")
    search_res = execute_tavily_search("AI agent developments 2026", max_results=2)
    print(search_res[:400] + "...\n")
    
    # 2. Test Summarize URL
    print("[2] Testing Tool 2: summarize_url...")
    sum_res = execute_url_summary("https://en.wikipedia.org/wiki/Artificial_intelligence", topic="AI overview")
    print(sum_res[:400] + "...\n")
    
    # 3. Test Save Report
    print("[3] Testing Tool 3: save_report...")
    save_res = execute_save_report("# Sample AI Report\n\nAI agents are evolving rapidly.", "sample_ai_test")
    print(save_res + "\n")
    
    print("[SUCCESS] All 3 tools tested successfully!\n")


def run_interactive_agent(topic: str):
    """Run full agent with ReAct loop, state memory, and HITL approval."""
    print(f"\n[LAUNCH] Autonomous Research Agent for topic: '{topic}'\n")
    
    app = build_research_graph()
    config = {"configurable": {"thread_id": "cli_session_1"}}
    
    initial_state = {
        "messages": [HumanMessage(content=f"Conduct thorough research on: '{topic}'. Synthesize a detailed Markdown research report.")],
        "research_topic": topic,
        "searched_queries": [],
        "urls_summarized": [],
        "report_draft": "",
        "is_approved": False,
        "human_feedback": "",
        "final_filepath": "",
        "step_history": []
    }
    
    state = app.invoke(initial_state, config)
    
    print("\n" + "="*50)
    print("  RESEARCH PROCESS COMPLETE - AGENT OUTPUT SUMMARY")
    print("="*50)
    
    searched = state.get("searched_queries", [])
    print(f"\n[SEARCH] Queries Searched by Agent: {searched}")
    
    urls = state.get("urls_summarized", [])
    print(f"[URL] URLs Summarized by Agent: {urls}\n")
    
    last_msg = state["messages"][-1].content
    print("[REPORT] Draft Report Generated by Agent:\n")
    print("-" * 50)
    print(last_msg)
    print("-" * 50)
    
    # Human-In-The-Loop Confirmation
    print("\n[STOP] HUMAN-IN-THE-LOOP CONFIRMATION")
    user_choice = input("Do you approve saving this report to file? (y/n): ").strip().lower()
    
    if user_choice in ["y", "yes"]:
        res = execute_save_report(last_msg, topic)
        print(f"\n[SUCCESS] {res}")
    else:
        print("\n[CANCEL] Report save cancelled by human user.")


if __name__ == "__main__":
    print_banner()
    has_keys = check_api_keys()
    
    if len(sys.argv) > 1 and sys.argv[1] == "--test-tools":
        if has_keys:
            test_individual_tools()
        sys.exit(0)
        
    topic_input = input("\nEnter research topic (or press Enter for default 'Agentic AI Workflows 2026'): ").strip()
    if not topic_input:
        topic_input = "Agentic AI Workflows 2026"
        
    if has_keys:
        run_interactive_agent(topic_input)
    else:
        print("To run the full agent, please add your GROQ_API_KEY and TAVILY_API_KEY to .env file.")
